// cms/angular/src/app/shared/weather-card/weather-card.component.ts
import {
  Component,
  HostBinding,
  HostListener,
  Input,
  NgZone,
  OnInit
} from "@angular/core";
import { capitalize, weatherIcons } from "../../helpers";

import { WeatherCardService } from "./weather-card.service";
import { first } from "rxjs/operators";
import format from "date-fns/format";

@Component({
  selector: "app-weather-card",
  template: `
    <div class="mb-4 card" *ngIf="weatherData">
      <div class="pb-0 card-body">
        <div class="d-flex mb-4 justify-content-between align-items-center">
          <div>
            <h5 class="mb-0 font-weight-bold">
              {{ weatherData.city.name }}, {{ weatherData.city.country }}
            </h5>
            <h6 class="mb-0">
              {{ getFormatedDate(weatherData.list[0].dt, "MMMM Do yyyy") }}
            </h6>
            <small>{{
              getCapitalizedWord(weatherData.list[0].weather[0].description)
            }}</small>
          </div>
          <div class="text-right">
            <h3 class="font-weight-light mb-0">
              <span>{{ weatherData.list[0].main.temp }}&deg;</span>
            </h3>
          </div>
        </div>
        <div
          class="d-flex justify-content-between align-items-center"
          style="flex-wrap: wrap;"
        >
          <div style="width: 50%;" *ngFor="let description of descriptionItems">
            <div class="d-flex mb-2 justify-content-between align-items-center">
              <span>{{ getCapitalizedWord(description) }}</span>
              <small class="px-2 d-inline-block">{{
                weatherData.list[0].main[description]
              }}</small>
            </div>
          </div>
        </div>
      </div>
      <div class="divider">
        <span class="divider-inner">
          <small>Forecast</small>
        </span>
      </div>
      <div class="pt-0 card-body">
        <div
          class="text-center justify-content-between align-items-center d-flex"
          style="flex-flow: initial;"
        >
          <div
            class="text-center mb-0 d-flex align-items-center justify-content-center flex-column"
            *ngFor="let day of weatherData.list"
          >
            <span style="display: block; margin: 2px 0px;">{{
              getFormatedDate(day.dt, "EEE")
            }}</span>
            <span style="display: block; margin: 2px 0px;">{{
              day.weather.description
            }}</span>
            <span style="display: block; margin: 2px 0px;">
              <span class="animated-icon">
                <app-animated-icon
                  style="width:24px;height:24px"
                  [path]="getWeatherIcon(day.weather[0].icon)"
                  autoPlay="true"
                  size="24px"
                ></app-animated-icon>
              </span>
            </span>
            <span style="display: block; margin: 2px 0px;"
              >{{ day.main.temp }}°</span
            >
          </div>
        </div>
      </div>
    </div>
  `
})
export class WeatherCardComponent implements OnInit {
  @Input() city: string;
  @Input() country: string;
  @Input() days: number;

  weatherData;
  descriptionItems;
  ngOnInit(): void {
    this.getWeatherData();
  }

  constructor(private weatherCardService: WeatherCardService) {}

  getWeatherData(): void {
    if (this.city && this.country && this.days) {
      this.weatherCardService
        .getData(this.city, this.country, this.days)
        .pipe(first())
        .subscribe(data => {
          this.weatherData = data;
          this.descriptionItems = Object.keys(this.weatherData.list[0].main);
        });
    }
  }

  getFormatedDate(date, dateFormat) {
    return format(date * 1000, dateFormat);
  }

  getCapitalizedWord(word) {
    return capitalize(word.replace(/_/g, " "));
  }

  getWeatherIcon(icon) {
    return weatherIcons[icon];
  }
}

// cms/react/components/core/WeatherCard.js
import { Card, CardBody } from "reactstrap";
import { capitalize, getWeatherIcon } from "../../lib/helpers";

import Divider from "./Divider";
import PropTypes from "prop-types";
import fetch from "../../lib/fetch";
import format from "date-fns/format";
import useSWR from "swr";

const DescriptionItem = ({ title, content }) => (
  <div className="d-flex mb-2 justify-content-between align-items-center">
    <span>{title}</span>
    <small className="px-2 d-inline-block">{content}</small>
  </div>
);

const ForecastItem = ({ content }) => (
  <span
    style={{
      display: "block",
      margin: "2px 0"
    }}
  >
    {content}
  </span>
);

const WeatherCard = ({ city, country, days }) => {
  const { data, error } = useSWR(
    `${process.env.baseUrl}api/weather?city=${city}&country=${country}&days=${days}`,
    fetch
  );

  if (error) return <div>Failed to load data</div>;
  if (!data) return <div>Loading...</div>;

  return (
    data && (
      <Card className="mb-4">
        <CardBody className="pb-0">
          <div className="d-flex mb-4 justify-content-between align-items-center">
            <div>
              <h5 className="mb-0 font-weight-bold">{`${data.city.name}, ${data.city.country}`}</h5>
              <h6 className="mb-0">
                {format(data.list[0].dt * 1000, "MMMM Do YYYY")}
              </h6>
              <small>{capitalize(data.list[0].weather[0].description)}</small>
            </div>
            <div className="text-right">
              <h3 className="font-weight-light mb-0">
                <span>{data.list[0].main.temp}&deg;</span>
              </h3>
            </div>
          </div>
          <div
            className="d-flex justify-content-between align-items-center"
            style={{ flexWrap: "wrap" }}
          >
            {Object.keys(data.list[0].main).map((key, index) => (
              <div key={index} style={{ width: "50%" }}>
                <DescriptionItem
                  title={capitalize(key.replace(/_/g, " "))}
                  content={data.list[0].main[key]}
                />
              </div>
            ))}
          </div>
        </CardBody>
        <Divider text="Forecast" />
        <CardBody className="pt-0">
          <div
            className="text-center justify-content-between align-items-center d-flex"
            style={{ flexFlow: "initial" }}
          >
            {data.list.map(
              (day, index) =>
                index !== 0 && (
                  <div
                    className="text-center mb-0 d-flex align-items-center justify-content-center flex-column"
                    key={index}
                  >
                    <ForecastItem content={format(day.dt * 1000, "ddd")} />
                    <ForecastItem content={day.weather.description} />
                    <ForecastItem
                      content={getWeatherIcon(
                        day.weather[0].icon,
                        24,
                        "rgba(0,0,0,.87)"
                      )}
                    />
                    <ForecastItem content={`${day.main.temp}°`} />
                  </div>
                )
            )}
          </div>
        </CardBody>
      </Card>
    )
  );
};

WeatherCard.propTypes = {
  city: PropTypes.string,
  country: PropTypes.string,
  days: PropTypes.number
};

export default WeatherCard;
